In [1]:
import pandas as pd
df=pd.read_csv("ai.csv",sep=',')
df

Day   Outlook  Temp Humidity    Wind Tennis
0    D1     Sunny   Hot     High    Weak     No
1    D2     Sunny   Hot     High  Strong     No
2    D3  Overcast   Hot     High    Weak    Yes
3    D4      Rain  Mild     High    Weak    Yes
4    D5      Rain  Cool   Normal    Weak    Yes
5    D6      Rain  Cool   Normal  Strong     No
6    D7  Overcast  Cool   Normal  Strong    Yes
7    D8     Sunny  Mild     High    Weak     No
8    D9     Sunny  Cool   Normal    Weak    Yes
9   D10      Rain  Mild   Normal    Weak    Yes
10  D11     Sunny  Mild   Normal  Strong    Yes
11  D12  Overcast  Mild     High  Strong    Yes
12  D13  Overcast   Hot   Normal    Weak    Yes
13  D14      Rain  Mild     High  Strong     No

In [2]:
df.drop('Day',axis=1,inplace=True)
df

Outlook  Temp Humidity    Wind Tennis
0      Sunny   Hot     High    Weak     No
1      Sunny   Hot     High  Strong     No
2   Overcast   Hot     High    Weak    Yes
3       Rain  Mild     High    Weak    Yes
4       Rain  Cool   Normal    Weak    Yes
5       Rain  Cool   Normal  Strong     No
6   Overcast  Cool   Normal  Strong    Yes
7      Sunny  Mild     High    Weak     No
8      Sunny  Cool   Normal    Weak    Yes
9       Rain  Mild   Normal    Weak    Yes
10     Sunny  Mild   Normal  Strong    Yes
11  Overcast  Mild     High  Strong    Yes
12  Overcast   Hot   Normal    Weak    Yes
13      Rain  Mild     High  Strong     No

In [3]:
# Import LabelEncoder
import numpy as np
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
Outlook_encoded=le.fit_transform(df['Outlook'])
print (Outlook_encoded)
#sunny 2 overcast 0 rain 1

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [4]:
Temp_encoded=le.fit_transform(df['Temp'])
print (Temp_encoded)
#hot 1 mild 2 cool 0

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [5]:
Humidity_encoded=le.fit_transform(df['Humidity'])
print (Humidity_encoded)
#high 0 normal 1

[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [8]:
Wind_encoded=le.fit_transform(df['Wind'])
print (Wind_encoded)
#weak 1 strong 0

[1 0 1 1 1 0 0 1 1 1 0 0 1 0]


In [6]:
Tennis_encoded=le.fit_transform(df['Tennis'])
print (Tennis_encoded)
#No 0 yes 1

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [12]:
F = zip(Outlook_encoded,Temp_encoded,Humidity_encoded,Wind_encoded)
print(set(F))

{(1, 0, 1, 1), (2, 0, 1, 1), (1, 0, 1, 0), (1, 2, 1, 1), (0, 2, 0, 0), (0, 1, 1, 1), (0, 0, 1, 0), (1, 2, 0, 0), (2, 1, 0, 0), (2, 2, 0, 1), (1, 2, 0, 1), (2, 1, 0, 1), (2, 2, 1, 0), (0, 1, 0, 1)}


In [13]:
features=list(zip(Outlook_encoded,Temp_encoded,Humidity_encoded,Wind_encoded)) #map the similar index of multiple containers so that they can be used just using as single entity. 
print (features)

[(2, 1, 0, 1), (2, 1, 0, 0), (0, 1, 0, 1), (1, 2, 0, 1), (1, 0, 1, 1), (1, 0, 1, 0), (0, 0, 1, 0), (2, 2, 0, 1), (2, 0, 1, 1), (1, 2, 1, 1), (2, 2, 1, 0), (0, 2, 0, 0), (0, 1, 1, 1), (1, 2, 0, 0)]


In [14]:
df.dtypes

Outlook     object
Temp        object
Humidity    object
Wind        object
Tennis      object
dtype: object

In [15]:
#6.1.a

from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,Tennis_encoded)

#Predict Output
#sunny cool high false
predicted= model.predict([[2,0,0,1]])
print ("Predicted Value:", predicted)

Predicted Value: [0]


In [16]:
#6.1.b
#rain hot high false
predicted= model.predict([[1,1,0,1]])
print ("Predicted Value:", predicted)

Predicted Value: [1]
