In [1]:
import numpy as np
from IPython.display import Markdown, display
X=np.array(([0.6,0.1],[0.2,0.3]),dtype=float)
y=np.array(([1,0],[0,1]))
#activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

#derivative of sigmoid
def sigmoid_derivative(p):
    return p*(1-p)

class NeuralNetwork:
    def __init__(self,X,y):
        self.input = X
        self.weight1 = np.array([[0.1,-0.2,0],[0.2,0.3,-0.4]])
        self.weight2 = np.array([[-0.4,0.1],[0.6,0.2],[-0.1,-0.2]])
        self.bias1 = np.array([[0.1,0.2,0.5]])
        self.bias2 = np.array([[0.1,0.6]])
        self.y = y
        self.output = np.zeros(self.y.shape)
    def feedforward(self):
        self.layer = sigmoid(np.add(np.dot(self.input,self.weight1),self.bias1))
        self.output = sigmoid(np.add(np.dot(self.layer, self.weight2),self.bias2))
        return self.output
    def backprop(self):
        d_weight2 = np.dot(self.layer.T,(0.1*2*(self.y-self.output)*sigmoid_derivative(self.output)))
        d_weight1 = np.dot(self.input.T, (np.dot(0.1*2*(self.y-self.output)*sigmoid_derivative(self.output),self.weight2.T)*sigmoid_derivative(self.layer)))
        
        self.weight1+=d_weight1
        self.weight2+=d_weight2
        
        k = np.dot(0.1*2*(self.y-self.output),sigmoid_derivative(self.layer))
        add_row = np.array([[0,0,0]])
        array_ = np.concatenate((k, add_row), axis=0)
        d_bias1 = np.dot(self.bias1,array_)
        d_bias2 = np.dot(self.bias2,(0.1*2*(self.y-self.output)*sigmoid_derivative(self.output)))
        
        self.bias1+=d_bias1
        self.bias2+=d_bias2
    def train(self,X,y):
        self.output = self.feedforward()
        self.backprop()

NN = NeuralNetwork(X,y)
for i in range(51):
    if i%50 == 0 or i==1:
        display(Markdown("**Result for::**"+str(i)+"\n**iteration**"))
        print ("for iteration # "+str(i)+"\n")
        print ("Input: \n"+str(X))
        print ("Actual Output: \n"+str(y))
        print ("Predicted Output: \n"+str(NN.feedforward()))
        print ("Loss: \n"+str(np.mean(np.square(y-NN.feedforward()))))
        print ("\n")
    NN.train(X,y)

**Result for::**0
**iteration**

for iteration # 0

Input: 
[[0.6 0.1]
 [0.2 0.3]]
Actual Output: 
[[1 0]
 [0 1]]
Predicted Output: 
[[0.53425386 0.65416086]
 [0.5399067  0.65659313]]
Loss: 
0.26356835288979574




**Result for::**1
**iteration**

for iteration # 1

Input: 
[[0.6 0.1]
 [0.2 0.3]]
Actual Output: 
[[1 0]
 [0 1]]
Predicted Output: 
[[0.52992199 0.65255898]
 [0.53553913 0.65498317]]
Loss: 
0.2631613344676721




**Result for::**50
**iteration**

for iteration # 50

Input: 
[[0.6 0.1]
 [0.2 0.3]]
Actual Output: 
[[1 0]
 [0 1]]
Predicted Output: 
[[0.23487579 0.78917535]
 [0.23735078 0.79118935]]
Loss: 
0.32703751761138666


