In [2]:
#required packages
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree
from sklearn.metrics import accuracy_score,precision_score, recall_score
import numpy as np
import matplotlib.pyplot as plt


In [3]:
df = pd.read_csv('ai.csv',sep=",")
df.head(5)

Day   Outlook  Temp Humidity    Wind Tennis
0  D1     Sunny   Hot     High    Weak     No
1  D2     Sunny   Hot     High  Strong     No
2  D3  Overcast   Hot     High    Weak    Yes
3  D4      Rain  Mild     High    Weak    Yes
4  D5      Rain  Cool   Normal    Weak    Yes

In [4]:
# Import LabelEncoder
import numpy as np
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
Outlook_encoded=le.fit_transform(df['Outlook'])
##pd.DataFrame(user_encoded)
#df22[0].unique()
print (Outlook_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [5]:
Temp_encoded=le.fit_transform(df['Temp'])
print (Temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [6]:
Humidity_encoded=le.fit_transform(df['Humidity'])
print (Humidity_encoded)

[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [7]:
Wind_encoded=le.fit_transform(df['Wind'])
print (Wind_encoded)

[1 0 1 1 1 0 0 1 1 1 0 0 1 0]


In [8]:
Tennis_encoded=le.fit_transform(df['Tennis'])
print (Tennis_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [9]:
features=list(zip(Outlook_encoded,Temp_encoded,Humidity_encoded,Wind_encoded)) 
print (features)

[(2, 1, 0, 1), (2, 1, 0, 0), (0, 1, 0, 1), (1, 2, 0, 1), (1, 0, 1, 1), (1, 0, 1, 0), (0, 0, 1, 0), (2, 2, 0, 1), (2, 0, 1, 1), (1, 2, 1, 1), (2, 2, 1, 0), (0, 2, 0, 0), (0, 1, 1, 1), (1, 2, 0, 0)]


In [10]:
X=features
y=df.Tennis

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=0)

In [12]:
# Create Decision Tree classifer object
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
predicted = clf.predict([[2,0,0,0]])
print ("Predicted Value:", predicted)

Predicted Value: ['No']


In [13]:
predicted = clf.predict([[1,1,0,0]])
print ("Predicted Value:", predicted)

Predicted Value: ['Yes']


In [16]:
print("Accuracy:",accuracy_score(y_test, y_pred)*100)

NameError: name 'y_pred' is not defined